HOST = "https://www.dustloop.com/wiki"

P4AU = {
    "Aigis": (f"{HOST}/index.php?title=P4AU/Aigis", f"{HOST}/images/thumb/8/8c/P4AU_Aigis_portrait.png/80px-P4AU_Aigis_portrait.png"),
    "Akihiko_Sanada": (f"{HOST}/index.php?title=P4AU/Akihiko_Sanada", f"{HOST}/images/thumb/4/47/P4AU_Akihiko_portrait.png/80px-P4AU_Akihiko_portrait.png"),
    "Chie_Satonaka": (f"{HOST}/index.php?title=P4AU/Chie_Satonaka", f"{HOST}/images/thumb/5/53/P4AU_Chie_portrait.png/80px-P4AU_Chie_portrait.png"),
    "Elizabeth": (f"{HOST}/index.php?title=P4AU/Elizabeth", f"{HOST}/images/thumb/0/07/P4AU_Elizabeth_portrait.png/80px-P4AU_Elizabeth_portrait.png"),
    "Junpei_Iori": (f"{HOST}/index.php?title=P4AU/Junpei_Iori", f"{HOST}/images/thumb/c/cb/P4AU_Junpei_portrait.png/80px-P4AU_Junpei_portrait.png"),
    "Kanji_Tatsumi": (f"{HOST}/index.php?title=P4AU/Kanji_Tatsumi", f"{HOST}/images/thumb/3/39/P4AU_Kanji_portrait.png/80px-P4AU_Kanji_portrait.png"),
    "Ken_Amada": (f"{HOST}/index.php?title=P4AU/Ken_Amada", f"{HOST}/images/thumb/c/ce/P4AU_Ken_portrait.png/80px-P4AU_Ken_portrait.png"),
    "Labrys": (f"{HOST}/index.php?title=P4AU/Labrys", f"{HOST}/images/thumb/5/5d/P4AU_Labrys_portrait.png/80px-P4AU_Labrys_portrait.png"),
    "Margaret": (f"{HOST}/index.php?title=P4AU/Margaret", f"{HOST}/images/thumb/6/69/P4AU_Margaret_portrait.png/80px-P4AU_Margaret_portrait.png"),
    "Marie": (f"{HOST}/index.php?title=P4AU/Marie", f"{HOST}/images/thumb/5/54/P4AU_Marie_portrait.png/80px-P4AU_Marie_portrait.png"),
    "Sho_MINAZUKI": (f"{HOST}/index.php?title=P4AU/Sho_MINAZUKI", f"{HOST}/images/thumb/2/2a/P4AU_PSho_portrait.png/80px-P4AU_PSho_portrait.png"),
    "Mitsuru_Kirijo": (f"{HOST}/index.php?title=P4AU/Mitsuru_Kirijo", f"{HOST}/images/thumb/5/54/P4AU_Mitsuru_portrait.png/80px-P4AU_Mitsuru_portrait.png"),
    "Naoto_Shirogane": (f"{HOST}/index.php?title=P4AU/Naoto_Shirogane", f"{HOST}/images/thumb/3/32/P4AU_Naoto_portrait.png/80px-P4AU_Naoto_portrait.png"),
    "Rise_Kujikawa": (f"{HOST}/index.php?title=P4AU/Rise_Kujikawa", f"{HOST}/images/thumb/b/b9/P4AU_Rise_portrait.png/80px-P4AU_Rise_portrait.png"),
    "Shadow_Labrys": (f"{HOST}/index.php?title=P4AU/Shadow_Labrys", f"{HOST}/images/thumb/4/43/P4AU_SLabrys_portrait.png/80px-P4AU_SLabrys_portrait.png"),
    "SHO_Minazuki": (f"{HOST}/index.php?title=P4AU/SHO_Minazuki", f"{HOST}/images/thumb/7/7b/P4AU_Sho_portrait.png/80px-P4AU_Sho_portrait.png"),
    "Teddie": (f"{HOST}/index.php?title=P4AU/Teddie", f"{HOST}/images/thumb/c/c2/P4AU_Teddie_portrait.png/80px-P4AU_Teddie_portrait.png"),
    "Tohru_Adachi": (f"{HOST}/index.php?title=P4AU/Tohru_Adachi", f"{HOST}/images/thumb/7/70/P4AU_Adachi_portrait.png/80px-P4AU_Adachi_portrait.png"),
    "Yosuke_Hanamura": (f"{HOST}/index.php?title=P4AU/Yosuke_Hanamura", f"{HOST}/images/thumb/2/23/P4AU_Yosuke_portrait.png/80px-P4AU_Yosuke_portrait.png"),
    "Yu_Narukami": (f"{HOST}/index.php?title=P4AU/Yu_Narukami", f"{HOST}/images/thumb/4/45/P4AU_Yu_portrait.png/80px-P4AU_Yu_portrait.png"),
    "Yukari_Takeba": (f"{HOST}/index.php?title=P4AU/Yukari_Takeba", f"{HOST}/images/thumb/4/40/P4AU_Yukari_portrait.png/80px-P4AU_Yukari_portrait.png"),
    "Yukiko_Amagi": (f"{HOST}/index.php?title=P4AU/Yukiko_Amagi", f"{HOST}/images/thumb/a/ae/P4AU_Yukiko_portrait.png/80px-P4AU_Yukiko_portrait.png")
    }

DBFZ = {
    "Android_16": (f"{HOST}/index.php?title=DBFZ/Android_16", f"{HOST}/images/thumb/6/6e/DBFZ_Android_16_Icon.png/81px-DBFZ_Android_16_Icon.png"),
    "Android_17": (f"{HOST}/index.php?title=DBFZ/Android_17", f"{HOST}/images/thumb/4/40/DBFZ_Android_17_Icon.png/81px-DBFZ_Android_17_Icon.png"),
    "Android_18": (f"{HOST}/index.php?title=DBFZ/Android_18", f"{HOST}/images/thumb/a/ac/DBFZ_Android_18_Icon.png/81px-DBFZ_Android_18_Icon.png"),
    "Android 21": (f"{HOST}/index.php?title=DBFZ/Android_21", f"{HOST}/images/thumb/5/5f/DBFZ_Android_21_Icon.png/81px-DBFZ_Android_21_Icon.png"),
    "Bardock": (f"{HOST}/index.php?title=DBFZ/Bardock", f"{HOST}/images/thumb/3/31/DBFZ_Bardock_Icon.png/81px-DBFZ_Bardock_Icon.png"),
    "Beerus": (f"{HOST}/index.php?title=DBFZ/Beerus", f"{HOST}/images/thumb/4/42/DBFZ_Beerus_Icon.png/81px-DBFZ_Beerus_Icon.png"),
    "Broley": (f"{HOST}/index.php?title=DBFZ/Broly", f"{HOST}/images/thumb/8/8f/DBFZ_Broly_Icon.png/81px-DBFZ_Broly_Icon.png"),
    "DBS_Broley": (f"{HOST}/index.php?title=DBFZ/DBS_Broly", f"{HOST}/wiki/images/thumb/0/0e/DBFZ_DBS_Broly_Icon.png/80px-DBFZ_DBS_Broly_Icon.png"),
    "Captain_Ginyu": (f"{HOST}/index.php?title=DBFZ/Captain_Ginyu", f"{HOST}/images/thumb/5/59/DBFZ_Captain_Ginyu_Icon.png/81px-DBFZ_Captain_Ginyu_Icon.png"),
    "Cell": (f"{HOST}/index.php?title=DBFZ/Cell", f"{HOST}/images/thumb/7/75/DBFZ_Cell_Icon.png/81px-DBFZ_Cell_Icon.png"),
    "Cooler": (f"{HOST}/index.php?title=DBFZ/Cooler", f"{HOST}/images/thumb/b/b3/DBFZ_Cooler_Icon.png/81px-DBFZ_Cooler_Icon.png"),
    "Frieza": (f"{HOST}/index.php?title=DBFZ/Frieza", f"{HOST}/images/thumb/a/a0/DBFZ_Frieza_Icon.png/81px-DBFZ_Frieza_Icon.png"),
    "SSB_Gogeta": (f"{HOST}/index.php?title=DBFZ/SSB_Gogeta", f"{HOST}/images/thumb/1/1a/DBFZ_SSB_Gogeta_Icon.png/80px-DBFZ_SSB_Gogeta_Icon.png"),
    "Teen_Gohan": (f"{HOST}/index.php?title=DBFZ/Teen_Gohan", f"{HOST}/images/thumb/2/2b/DBFZ_Teen_Gohan_Icon.png/81px-DBFZ_Teen_Gohan_Icon.png"),
    "Adult_Gohan": (f"{HOST}/index.php?title=DBFZ/Adult_Gohan", f"{HOST}/images/thumb/1/14/DBFZ_Adult_Gohan_Icon.png/81px-DBFZ_Adult_Gohan_Icon.png"),
    "Goku": (f"{HOST}/index.php?title=DBFZ/Goku", f"{HOST}/images/thumb/b/bb/DBFZ_Goku_Icon.png/81px-DBFZ_Goku_Icon.png"),
    "SS_Goku": (f"{HOST}/index.php?title=DBFZ/SS_Goku", f"{HOST}/images/thumb/8/87/DBFZ_SS_Goku_Icon.png/81px-DBFZ_SS_Goku_Icon.png"),
    "SSB_Goku": (f"{HOST}/index.php?title=DBFZ/SSB_Goku", f"{HOST}/images/thumb/9/94/DBFZ_SSB_Goku_Icon.png/81px-DBFZ_SSB_Goku_Icon.png"),
    "UI_Goku": (f"{HOST}/index.php?title=DBFZ/UI_Goku", f"{HOST}/images/thumb/9/90/DBFZ_UI_Goku_Icon.png/80px-DBFZ_UI_Goku_Icon.png"),
    "GT_Goku": (f"{HOST}/index.php?title=DBFZ/GT_Goku", f"{HOST}/images/thumb/0/01/DBFZ_GT_Goku_Icon.png/81px-DBFZ_GT_Goku_Icon.png"),
    "Goku_Black": (f"{HOST}/index.php?title=DBFZ/Goku_Black", f"{HOST}/images/thumb/a/a3/DBFZ_Goku_Black_Icon.png/81px-DBFZ_Goku_Black_Icon.png"),
    "Gotenks": (f"{HOST}/index.php?title=DBFZ/Gotenks", f"{HOST}/images/thumb/f/f2/DBFZ_Gotenks_Icon.png/81px-DBFZ_Gotenks_Icon.png"),
    "Hit": (f"{HOST}/index.php?title=DBFZ/Hit", f"{HOST}/images/thumb/d/dd/DBFZ_Hit_Icon.png/81px-DBFZ_Hit_Icon.png"),
    "Janemba": (f"{HOST}/index.php?title=DBFZ/Janemba", f"{HOST}/images/thumb/a/a3/DBFZ_Janemba_Icon.png/80px-DBFZ_Janemba_Icon.png"),
    "Jiren": (f"{HOST}/index.php?title=DBFZ/Jiren", f"{HOST}/images/thumb/c/c7/DBFZ_Jiren_Icon.png/81px-DBFZ_Jiren_Icon.png"),
    "Kefla": (f"{HOST}/index.php?title=DBFZ/Kefla", f"{HOST}/images/thumb/5/5d/DBFZ_Kefla_Icon.png/80px-DBFZ_Kefla_Icon.png"),
    "Kid_Buu": (f"{HOST}/index.php?title=DBFZ/Kid_Buu", f"{HOST}/images/thumb/a/a4/DBFZ_Kid_Buu_Icon.png/81px-DBFZ_Kid_Buu_Icon.png"),
    "Krilin": (f"{HOST}/index.php?title=DBFZ/Krillin", f"{HOST}/images/thumb/5/51/DBFZ_Krillin_Icon.png/81px-DBFZ_Krillin_Icon.png"),
    "Majin_Buu": (f"{HOST}/index.php?title=DBFZ/Majin_Buu", f"{HOST}/images/thumb/d/d0/DBFZ_Majin_Buu_Icon.png/81px-DBFZ_Majin_Buu_Icon.png"),
    "Master_Roshi": (f"{HOST}/index.php?title=DBFZ/Master_Roshi", f"{HOST}/images/thumb/8/8d/DBFZ_Master_Roshi_Icon.png/80px-DBFZ_Master_Roshi_Icon.png"),
    "Nappa": (f"{HOST}/index.php?title=DBFZ/Nappa", f"{HOST}/images/thumb/0/00/DBFZ_Nappa_Icon.png/81px-DBFZ_Nappa_Icon.png"),
    "Piccolo": (f"{HOST}/index.php?title=DBFZ/Piccolo", f"{HOST}/images/thumb/c/c8/DBFZ_Piccolo_Icon.png/81px-DBFZ_Piccolo_Icon.png"),
    "Tien": (f"{HOST}/index.php?title=DBFZ/Tien", f"{HOST}/images/thumb/8/85/DBFZ_Tien_Icon.png/81px-DBFZ_Tien_Icon.png"),
    "Trunks": (f"{HOST}/index.php?title=DBFZ/Trunks", f"{HOST}/images/thumb/b/b8/DBFZ_Trunks_Icon.png/81px-DBFZ_Trunks_Icon.png"),
    "Vegeta": (f"{HOST}/index.php?title=DBFZ/Vegeta", f"{HOST}/images/thumb/6/66/DBFZ_Vegeta_Icon.png/81px-DBFZ_Vegeta_Icon.png"),
    "SS_Vegeta": (f"{HOST}/index.php?title=DBFZ/SS_Vegeta", f"{HOST}/images/thumb/8/8d/DBFZ_SS_Vegeta_Icon.png/81px-DBFZ_SS_Vegeta_Icon.png"),
    "SSB_Vegeta": (f"{HOST}/index.php?title=DBFZ/SSB_Vegeta", f"{HOST}/images/thumb/9/92/DBFZ_SSB_Vegeta_Icon.png/81px-DBFZ_SSB_Vegeta_Icon.png"),
    "SSB_Vegito": (f"{HOST}/index.php?title=DBFZ/SSB_Vegito", f"{HOST}/images/thumb/8/89/DBFZ_SSB_Vegito_Icon.png/81px-DBFZ_SSB_Vegito_Icon.png"),
    "Videl": (f"{HOST}/index.php?title=DBFZ/Videl", f"{HOST}/images/thumb/0/0d/DBFZ_Videl_Icon.png/81px-DBFZ_Videl_Icon.png"),
    "Yamcha": (f"{HOST}/index.php?title=DBFZ/Yamcha", f"{HOST}/images/thumb/0/08/DBFZ_Yamcha_Icon.png/81px-DBFZ_Yamcha_Icon.png"),
    "Fused_Zamasu": (f"{HOST}/index.php?title=DBFZ/Fused_Zamasu", f"{HOST}/images/thumb/1/17/DBFZ_Fused_Zamasu_Icon.png/81px-DBFZ_Fused_Zamasu_Icon.png"),
}

GBVS = {
    "Beelzebub": (f"{HOST}/index.php?title=GBVS/Beelzebub", f"{HOST}/images/f/fd/GBVS_Beelzebub_Icon.png"),
    "Belial": (f"{HOST}/index.php?title=GBVS/Belial", f"{HOST}/images/b/bb/GBVS_Belial_Icon.png"),
    "Cagliostro": (f"{HOST}/index.php?title=GBVS/Cagliostro", f"{HOST}/images/c/c7/GBVS_Cagliostro_Icon.png"),
    "Charlotta": (f"{HOST}/index.php?title=GBVS/Charlotta", f"{HOST}/images/4/46/GBVS_Charlotta_Icon.png"),
    "Djeeta": (f"{HOST}/index.php?title=GBVS/Djeeta", f"{HOST}/images/1/15/GBVS_Djeeta_Icon.png"),
    "Ferry": (f"{HOST}/index.php?title=GBVS/Ferry", f"{HOST}/images/a/a0/GBVS_Ferry_Icon.png"),
    "Gran": (f"{HOST}/index.php?title=GBVS/Gran", f"{HOST}/images/2/21/GBVS_Gran_Icon.png"),
    "Katalina": (f"{HOST}/index.php?title=GBVS/Katalina", f"{HOST}/images/a/aa/GBVS_Katalina_Icon.png"),
    "Ladiva": (f"{HOST}/index.php?title=GBVS/Ladiva", f"{HOST}/images/5/52/GBVS_Ladiva_Icon.png"),
    "Lancelot": (f"{HOST}/index.php?title=GBVS/Lancelot", f"{HOST}/images/2/26/GBVS_Lancelot_Icon.png"),
    "Lowain": (f"{HOST}/index.php?title=GBVS/Lowain", f"{HOST}/images/3/3c/GBVS_Lowain_Icon.png"),
    "Metera": (f"{HOST}/index.php?title=GBVS/Metera", f"{HOST}/images/5/50/GBVS_Metera_Icon.png"),
    "Narmaya": (f"{HOST}/index.php?title=GBVS/Narmaya", f"{HOST}/images/5/5e/GBVS_Narmaya_Icon.png"),
    "Percival": (f"{HOST}/index.php?title=GBVS/Percival", f"{HOST}/images/3/3d/GBVS_Percival_Icon.png"),
    "Soriz": (f"{HOST}/index.php?title=GBVS/Soriz", f"{HOST}/images/7/7d/GBVS_Soriz_Icon.png"),
    "Vaseraga": (f"{HOST}/index.php?title=GBVS/Vaseraga", f"{HOST}/images/5/57/GBVS_Vaseraga_Icon.png"),
    "Yuel": (f"{HOST}/index.php?title=GBVS/Yuel", f"{HOST}/images/4/45/GBVS_Yuel_Icon.png"),
    "Zeta": (f"{HOST}/index.php?title=GBVS/Zeta", f"{HOST}/images/f/f0/GBVS_Zeta_Icon.png"),
    "Zooey": (f"{HOST}/index.php?title=GBVS/Zooey" f"{HOST}/images/f/f5/GBVS_Zooey_Icon.png"),
}

"""BBTAG = {
    # Blaz Blue #
    "Ragna_the_Bloodedge": (f"{HOST}/index.php?title=BBTag/Ragna_the_Bloodedge",
    "Jin_Kisaragi": (f"{HOST}/index.php?title=BBTag/Jin_Kisaragi",
    "Noel_Vermillion": (f"{HOST}/index.php?title=BBTag/Noel_Vermillion",
    "Rachel_Alucard": (f"{HOST}/index.php?title=BBTag/Rachel_Alucard",
    "Iron_Tager": (f"{HOST}/index.php?title=BBTag/Iron_Tager",
    "Hakumen": (f"{HOST}/index.php?title=BBTag/Hakumen",
    "Nu-13": (f"{HOST}/index.php?title=BBTag/Nu-13",
    "Hazama": (f"{HOST}/index.php?title=BBTag/Hazama",
    "Makoto_Nanaya": (f"{HOST}/index.php?title=BBTag/Makoto_Nanaya",
    "Platinum_the_Trinity": (f"{HOST}/index.php?title=BBTag/Platinum_the_Trinity",
    "Izayoi": (f"{HOST}/index.php?title=BBTag/Izayoi",
    "Azrael": (f"{HOST}/index.php?title=BBTag/Azrael",
    "Celica_A._Mercury": (f"{HOST}/index.php?title=BBTag/Celica_A._Mercury",
    "Nine_the_Phantom": (f"{HOST}/index.php?title=BBTag/Nine_the_Phantom",
    "Naoto_Kurogane": (f"{HOST}/index.php?title=BBTag/Naoto_Kurogane",
    "Susano'o": (f"{HOST}/index.php?title=BBTag/Susano'o",
    "Es": (f"{HOST}/index.php?title=BBTag/Es",
    "Mai_Natsume": (f"{HOST}/index.php?title=BBTag/Mai_Natsume",
    "Jubei": (f"{HOST}/index.php?title=BBTag/Jubei",

    # Persona 4 #
    "Yu_Narukami": (f"{HOST}/index.php?title=BBTag/Yu_Narukami",
    "Yosuke_Hanamura": (f"{HOST}/index.php?title=BBTag/Yosuke_Hanamura",
    "Chie_Satonaka": (f"{HOST}/index.php?title=BBTag/Chie_Satonaka",
    "Yukiko_Amagi": (f"{HOST}/index.php?title=BBTag/Yukiko_Amagi",
    "Kanji_Tatsumi": (f"{HOST}/index.php?title=BBTag/Kanji_Tatsumi",
    "Teddie": (f"{HOST}/index.php?title=BBTag/Teddie",
    "Naoto_Shirogane": (f"{HOST}/index.php?title=BBTag/Naoto_Shirogane",
    "Mitsuru_Kirijo": (f"{HOST}/index.php?title=BBTag/Mitsuru_Kirijo",
    "Akihiko_Sanada": (f"{HOST}/index.php?title=BBTag/Akihiko_Sanada",
    "Aegis": (f"{HOST}/index.php?title=BBTag/Aegis",
    "Elizabeth": (f"{HOST}/index.php?title=BBTag/Elizabeth",
    "Labrys": (f"{HOST}/index.php?title=BBTag/Labrys",
    "Tohru_Adachi": (f"{HOST}/index.php?title=BBTag/Tohru_Adachi", 

    # Under Night In-Birth #
    "Hyde": (f"{HOST}/index.php?title=BBTag/Hyde",
    "Linne": (f"{HOST}/index.php?title=BBTag/Linne",
    "Waldstein": (f"{HOST}/index.php?title=BBTag/Waldstein",
    "Carmine": (f"{HOST}/index.php?title=BBTag/Carmine",
    "Orie": (f"{HOST}/index.php?title=BBTag/Orie",
    "Gordeau": (f"{HOST}/index.php?title=BBTag/Gordeau",
    "Merkava": (f"{HOST}/index.php?title=BBTag/Merkava",
    "Vatista": (f"{HOST}/index.php?title=BBTag/Vatista",
    "Seth": (f"{HOST}/index.php?title=BBTag/Seth",
    "Yuzuriha": (f"{HOST}/index.php?title=BBTag/Yuzuriha",
    "Hilda": (f"{HOST}/index.php?title=BBTag/Hilda",
    "Mika": (f"{HOST}/index.php?title=BBTag/Mika",
    # RWBY #
    "Ruby_Rose": (f"{HOST}/index.php?title=BBTag/Ruby_Rose",
    "Weiss_Schnee": (f"{HOST}/index.php?title=BBTag/Weiss_Schnee",
    "Blake_Belladonna": (f"{HOST}/index.php?title=BBTag/Blake_Belladonna",
    "Yang_Xiao_Long": (f"{HOST}/index.php?title=BBTag/Yang_Xiao_Long",
    "Neo_Politan": (f"{HOST}/index.php?title=BBTag/Neo_Politan",

    # Others #
    "Heart_Aino": (f"{HOST}/index.php?title=BBTag/Heart_Aino",
    "Yumi": (f"{HOST}/index.php?title=BBTag/Yumi",
    "Akatsuki": (f"{HOST}/index.php?title=BBTag/Akatsuki",
    "Blitztank": (f"{HOST}/index.php?title=BBTag/Blitztank"
}

GGXRDREV2 = {
    "Answer": (f"{HOST}/index.php?title=GGXRD-R2/Answer",
    "Axl_Low": (f"{HOST}/index.php?title=GGXRD-R2/Axl_Low",
    "Baiken": (f"{HOST}/index.php?title=GGXRD-R2/Baiken",
    "Bedman": (f"{HOST}/index.php?title=GGXRD-R2/Bedman",
    "Chipp_Zanuff": (f"{HOST}/index.php?title=GGXRD-R2/Chipp_Zanuff",
    "Dizzy": (f"{HOST}/index.php?title=GGXRD-R2/Dizzy",
    "Elphelt_Valentine": (f"{HOST}/index.php?title=GGXRD-R2/Elphelt_Valentine",
    "Faust": (f"{HOST}/index.php?title=GGXRD-R2/Faust",
    "I-No": (f"{HOST}/index.php?title=GGXRD-R2/I-No",
    "Jack-O'": (f"{HOST}/index.php?title=GGXRD-R2/Jack-O'",
    "Jam_Kuradoberi": (f"{HOST}/index.php?title=GGXRD-R2/Jam_Kuradoberi",
    "Johnny": (f"{HOST}/index.php?title=GGXRD-R2/Johnny",
    "Kum_Haehyun": (f"{HOST}/index.php?title=GGXRD-R2/Kum_Haehyun",
    "Ky_Kiske": (f"{HOST}/index.php?title=GGXRD-R2/Ky_Kiske",
    "Leo_Whitefang": (f"{HOST}/index.php?title=GGXRD-R2/Leo_Whitefang",
    "May": (f"{HOST}/index.php?title=GGXRD-R2/May",
    "Millia_Rage": (f"{HOST}/index.php?title=GGXRD-R2/Millia_Rage",
    "Potemkin": (f"{HOST}/index.php?title=GGXRD-R2/Potemkin",
    "Ramlethal_Valentine": (f"{HOST}/index.php?title=GGXRD-R2/Ramlethal_Valentine",
    "Raven": (f"{HOST}/index.php?title=GGXRD-R2/Raven",
    "Sin_Kiske": (f"{HOST}/index.php?title=GGXRD-R2/Sin_Kiske",
    "Slayer": (f"{HOST}/index.php?title=GGXRD-R2/Slayer",
    "Sol_Badguy": (f"{HOST}/index.php?title=GGXRD-R2/Sol_Badguy",
    "Venom": (f"{HOST}/index.php?title=GGXRD-R2/Venom",
    "Zato-1": (f"{HOST}/index.php?title=GGXRD-R2/Zato-1"
}

BBCF = {
    "Amane_Nishiki": (f"{HOST}/index.php?title=BBCF/Amane_Nishiki",
    "Arakune": (f"{HOST}/index.php?title=BBCF/Arakune",
    "Azrael": (f"{HOST}/index.php?title=BBCF/Azrael",
    "Bang_Shishigami": (f"{HOST}/index.php?title=BBCF/Bang_Shishigami",
    "Bullet": (f"{HOST}/index.php?title=BBCF/Bullet",
    "Carl_Clover": (f"{HOST}/index.php?title=BBCF/Carl_Clover",
    "Celica_A._Mercury": (f"{HOST}/index.php?title=BBCF/Celica_A._Mercury",
    "Es": (f"{HOST}/index.php?title=BBCF/Es",
    "Hakumen": (f"{HOST}/index.php?title=BBCF/Hakumen",
    "Hazama": (f"{HOST}/index.php?title=BBCF/Hazama",
    "Hibiki_Kohaku": (f"{HOST}/index.php?title=BBCF/Hibiki_Kohaku",
    "Izanami": (f"{HOST}/index.php?title=BBCF/Izanami",
    "Izayoi": (f"{HOST}/index.php?title=BBCF/Izayoi",
    "Jin_Kisaragi": (f"{HOST}/index.php?title=BBCF/Jin_Kisaragi",
    "Jubei": (f"{HOST}/index.php?title=BBCF/Jubei",
    "Kagura_Mutsuki": (f"{HOST}/index.php?title=BBCF/Kagura_Mutsuki",
    "Kokonoe": (f"{HOST}/index.php?title=BBCF/Kokonoe",
    "Litchi_Faye_Ling": (f"{HOST}/index.php?title=BBCF/Litchi_Faye_Ling",
    "Makoto_Nanaya": (f"{HOST}/index.php?title=BBCF/Makoto_Nanaya",
    "Mai_Natsume": (f"{HOST}/index.php?title=BBCF/Mai_Natsume",
    "Naoto_Kurogane": (f"{HOST}/index.php?title=BBCF/Naoto_Kurogane",
    "Nine_the_Phantom": (f"{HOST}/index.php?title=BBCF/Nine_the_Phantom",
    "Noel_Vermillion": (f"{HOST}/index.php?title=BBCF/Noel_Vermillion",
    "Platinum_the_Trinity": (f"{HOST}/index.php?title=BBCF/Platinum_the_Trinity",
    "Rachel_Alucard": (f"{HOST}/index.php?title=BBCF/Rachel_Alucard",
    "Ragna_the_Bloodedge": (f"{HOST}/index.php?title=BBCF/Ragna_the_Bloodedge",
    "Relius_Clover": (f"{HOST}/index.php?title=BBCF/Relius_Clover",
    "Susano'o": (f"{HOST}/index.php?title=BBCF/Susano'o",
    "Iron_Tager": (f"{HOST}/index.php?title=BBCF/Iron_Tager",
    "Taokaka": (f"{HOST}/index.php?title=BBCF/Taokaka",
    "Tsubaki_Yayoi": (f"{HOST}/index.php?title=BBCF/Tsubaki_Yayoi",
    "Yuuki_Terumi": (f"{HOST}/index.php?title=BBCF/Yuuki_Terumi",
    "Valkenhayn_R._Hellsing": (f"{HOST}/index.php?title=BBCF/Valkenhayn_R._Hellsing",
    "Lambda-11": (f"{HOST}/index.php?title=BBCF/Lambda-11",
    "Mu-12": (f"{HOST}/index.php?title=BBCF/Mu-12",
    "Nu-13": (f"{HOST}/index.php?title=BBCF/Nu-13"
}

UNICLR = {
    "Hyde": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Hyde",
    "Linne": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Linne",
    "Waldstein": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Waldstein",
    "Carmine": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Carmine",
    "Orie": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Orie",
    "Gordeau": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Gordeau",
    "Merkava": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Merkava",
    "Vatista": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Vatista",
    "Seth": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Seth",
    "Yuzuriha": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Yuzuriha",
    "Hilda": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Hilda",
    "Chaos": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Chaos",
    "Nanase": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Nanase",
    "Byakuya": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Byakuya",
    "Phonon": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Phonon",
    "Mika": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Mika",
    "Wagner": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Wagner",
    "Enkidu": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Enkidu",
    "Londrekia": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Londrekia",
    "Eltnum": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Eltnum",
    "Akatsuki": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Akatsuki"
}

GAMES = {
    "P4AU": P4AU,
    "DBFZ": DBFZ,
    "GBVS": GBVS,
    "BBTAG": BBTAG,
    "GGXRDREV2": GGXRDREV2,
    "BBCF": BBCF,
    "UNICLR": UNICLR
} """

GAMES = {
    "P4AU": P4AU,
    "DBFZ": DBFZ
}
