P4AU = {
    "Aigis": "https://www.dustloop.com/wiki/index.php?title=P4AU/Aigis",
    "Akihiko_Sanada": "https://www.dustloop.com/wiki/index.php?title=P4AU/Akihiko_Sanada",
    "Chie_Satonaka": "https://www.dustloop.com/wiki/index.php?title=P4AU/Chie_Satonaka",
    "Elizabeth": "https://www.dustloop.com/wiki/index.php?title=P4AU/Elizabeth",
    "Junpei_Iori": "https://www.dustloop.com/wiki/index.php?title=P4AU/Junpei_Iori",
    "Kanji_Tatsumi": "https://www.dustloop.com/wiki/index.php?title=P4AU/Kanji_Tatsumi",
    "Ken_Amada": "https://www.dustloop.com/wiki/index.php?title=P4AU/Ken_Amada",
    "Labrys": "https://www.dustloop.com/wiki/index.php?title=P4AU/Labrys",
    "Margaret": "https://www.dustloop.com/wiki/index.php?title=P4AU/Margaret",
    "Marie": "https://www.dustloop.com/wiki/index.php?title=P4AU/Marie",
    "Sho_MINAZUKI": "https://www.dustloop.com/wiki/index.php?title=P4AU/Sho_MINAZUKI",
    "Mitsuru_Kirijo": "https://www.dustloop.com/wiki/index.php?title=P4AU/Mitsuru_Kirijo",
    "Naoto_Shirogane": "https://www.dustloop.com/wiki/index.php?title=P4AU/Naoto_Shirogane",
    "Rise_Kujikawa": "https://www.dustloop.com/wiki/index.php?title=P4AU/Rise_Kujikawa",
    "Shadow_Labrys": "https://www.dustloop.com/wiki/index.php?title=P4AU/Shadow_Labrys",
    "SHO_Minazuki": "https://www.dustloop.com/wiki/index.php?title=P4AU/SHO_Minazuki",
    "Teddie": "https://www.dustloop.com/wiki/index.php?title=P4AU/Teddie",
    "Tohru_Adachi": "https://www.dustloop.com/wiki/index.php?title=P4AU/Tohru_Adachi",
    "Yosuke_Hanamura": "https://www.dustloop.com/wiki/index.php?title=P4AU/Yosuke_Hanamura",
    "Yu_Narukami": "https://www.dustloop.com/wiki/index.php?title=P4AU/Yu_Narukami",
    "Yukari_Takeba": "https://www.dustloop.com/wiki/index.php?title=P4AU/Yukari_Takeba",
    "Yukiko_Amagi": "https://www.dustloop.com/wiki/index.php?title=P4AU/Yukiko_Amagi"
}

DBFZ = {
    "Android_16": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Android_16",
    "Android_17": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Android_17",
    "Android_18": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Android_18",
    "Android 21": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Android_21",
    "Bardock": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Bardock",
    "Beerus": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Beerus",
    "Broley": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Broly",
    "DBS_Broley": "https://www.dustloop.com/wiki/index.php?title=DBFZ/DBS_Broly",
    "Captain_Ginyu": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Captain_Ginyu",
    "Cell": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Cell",
    "Cooler": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Cooler",
    "Frieza": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Frieza",
    "SSB_Gogeta": "https://www.dustloop.com/wiki/index.php?title=DBFZ/SSB_Gogeta",
    "Teen_Gohan": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Teen_Gohan",
    "Adult_Gohan": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Adult_Gohan",
    "Goku": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Goku",
    "SS_Goku": "https://www.dustloop.com/wiki/index.php?title=DBFZ/SS_Goku",
    "SSB_Goku": "https://www.dustloop.com/wiki/index.php?title=DBFZ/SSB_Goku",
    "UI_Goku": "https://www.dustloop.com/wiki/index.php?title=DBFZ/UI_Goku",
    "GT_Goku": "https://www.dustloop.com/wiki/index.php?title=DBFZ/GT_Goku",
    "Goku_Black": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Goku_Black",
    "Gotenks": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Gotenks",
    "Hit": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Hit",
    "Janemba": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Janemba",
    "Jiren": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Jiren",
    "Kefla": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Kefla",
    "Kid_Buu": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Kid_Buu",
    "Krilin": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Krillin",
    "Majin_Buu": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Majin_Buu",
    "Nappa": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Nappa",
    "Piccolo": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Piccolo",
    "Tien": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Tien",
    "Trunks": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Trunks",
    "Vegeta": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Vegeta",
    "SS_Vegeta": "https://www.dustloop.com/wiki/index.php?title=DBFZ/SS_Vegeta",
    "SSB_Vegeta": "https://www.dustloop.com/wiki/index.php?title=DBFZ/SSB_Vegeta",
    "SSB_Vegito": "https://www.dustloop.com/wiki/index.php?title=DBFZ/SSB_Vegito",
    "Videl": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Videl",
    "Yamcha": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Yamcha",
    "Fused_Zamasu": "https://www.dustloop.com/wiki/index.php?title=DBFZ/Fused_Zamasu"
}

GBVS = {
    "Beelzebub": "https://www.dustloop.com/wiki/index.php?title=GBVS/Beelzebub",
    "Belial": "https://www.dustloop.com/wiki/index.php?title=GBVS/Belial",
    "Charlotta": "https://www.dustloop.com/wiki/index.php?title=GBVS/Charlotta",
    "Djeeta": "https://www.dustloop.com/wiki/index.php?title=GBVS/Djeeta",
    "Ferry": "https://www.dustloop.com/wiki/index.php?title=GBVS/Ferry",
    "Gran": "https://www.dustloop.com/wiki/index.php?title=GBVS/Gran",
    "Katalina": "https://www.dustloop.com/wiki/index.php?title=GBVS/Katalina",
    "Ladiva": "https://www.dustloop.com/wiki/index.php?title=GBVS/Ladiva",
    "Lancelot": "https://www.dustloop.com/wiki/index.php?title=GBVS/Lancelot",
    "Lowain": "https://www.dustloop.com/wiki/index.php?title=GBVS/Lowain",
    "Metera": "https://www.dustloop.com/wiki/index.php?title=GBVS/Metera",
    "Narmaya": "https://www.dustloop.com/wiki/index.php?title=GBVS/Narmaya",
    "Percival": "https://www.dustloop.com/wiki/index.php?title=GBVS/Percival",
    "Soriz": "https://www.dustloop.com/wiki/index.php?title=GBVS/Soriz",
    "Vaseraga": "https://www.dustloop.com/wiki/index.php?title=GBVS/Vaseraga",
    "Zeta": "https://www.dustloop.com/wiki/index.php?title=GBVS/Zeta",
    "Zooey": "https://www.dustloop.com/wiki/index.php?title=GBVS/Zooey"
}

BBTAG = {
    # BlazBlue #
    "Ragna_the_Bloodedge": "https://www.dustloop.com/wiki/index.php?title=BBTag/Ragna_the_Bloodedge",
    "Jin_Kisaragi": "https://www.dustloop.com/wiki/index.php?title=BBTag/Jin_Kisaragi",
    "Noel_Vermillion": "https://www.dustloop.com/wiki/index.php?title=BBTag/Noel_Vermillion",
    "Rachel_Alucard": "https://www.dustloop.com/wiki/index.php?title=BBTag/Rachel_Alucard",
    "Iron_Tager": "https://www.dustloop.com/wiki/index.php?title=BBTag/Iron_Tager",
    "Hakumen": "https://www.dustloop.com/wiki/index.php?title=BBTag/Hakumen",
    "Nu-13": "https://www.dustloop.com/wiki/index.php?title=BBTag/Nu-13",
    "Hazama": "https://www.dustloop.com/wiki/index.php?title=BBTag/Hazama",
    "Makoto_Nanaya": "https://www.dustloop.com/wiki/index.php?title=BBTag/Makoto_Nanaya",
    "Platinum_the_Trinity": "https://www.dustloop.com/wiki/index.php?title=BBTag/Platinum_the_Trinity",
    "Izayoi": "https://www.dustloop.com/wiki/index.php?title=BBTag/Izayoi",
    "Azrael": "https://www.dustloop.com/wiki/index.php?title=BBTag/Azrael",
    "Celica_A._Mercury": "https://www.dustloop.com/wiki/index.php?title=BBTag/Celica_A._Mercury",
    "Nine_the_Phantom": "https://www.dustloop.com/wiki/index.php?title=BBTag/Nine_the_Phantom",
    "Naoto_Kurogane": "https://www.dustloop.com/wiki/index.php?title=BBTag/Naoto_Kurogane",
    "Susano'o": "https://www.dustloop.com/wiki/index.php?title=BBTag/Susano'o",
    "Es": "https://www.dustloop.com/wiki/index.php?title=BBTag/Es",
    "Mai_Natsume": "https://www.dustloop.com/wiki/index.php?title=BBTag/Mai_Natsume",
    "Jubei": "https://www.dustloop.com/wiki/index.php?title=BBTag/Jubei",

    # Persona 4 #
    "Yu_Narukami": "https://www.dustloop.com/wiki/index.php?title=BBTag/Yu_Narukami",
    "Yosuke_Hanamura": "https://www.dustloop.com/wiki/index.php?title=BBTag/Yosuke_Hanamura",
    "Chie_Satonaka": "https://www.dustloop.com/wiki/index.php?title=BBTag/Chie_Satonaka",
    "Yukiko_Amagi": "https://www.dustloop.com/wiki/index.php?title=BBTag/Yukiko_Amagi",
    "Kanji_Tatsumi": "https://www.dustloop.com/wiki/index.php?title=BBTag/Kanji_Tatsumi",
    "Teddie": "https://www.dustloop.com/wiki/index.php?title=BBTag/Teddie",
    "Naoto_Shirogane": "https://www.dustloop.com/wiki/index.php?title=BBTag/Naoto_Shirogane",
    "Mitsuru_Kirijo": "https://www.dustloop.com/wiki/index.php?title=BBTag/Mitsuru_Kirijo",
    "Akihiko_Sanada": "https://www.dustloop.com/wiki/index.php?title=BBTag/Akihiko_Sanada",
    "Aegis": "https://www.dustloop.com/wiki/index.php?title=BBTag/Aegis",
    "Elizabeth": "https://www.dustloop.com/wiki/index.php?title=BBTag/Elizabeth",
    "Labrys": "https://www.dustloop.com/wiki/index.php?title=BBTag/Labrys",
    "Tohru_Adachi": "https://www.dustloop.com/wiki/index.php?title=BBTag/Tohru_Adachi",

    # Under Night In-Birth #
    "Hyde": "https://www.dustloop.com/wiki/index.php?title=BBTag/Hyde",
    "Linne": "https://www.dustloop.com/wiki/index.php?title=BBTag/Linne",
    "Waldstein": "https://www.dustloop.com/wiki/index.php?title=BBTag/Waldstein",
    "Carmine": "https://www.dustloop.com/wiki/index.php?title=BBTag/Carmine",
    "Orie": "https://www.dustloop.com/wiki/index.php?title=BBTag/Orie",
    "Gordeau": "https://www.dustloop.com/wiki/index.php?title=BBTag/Gordeau",
    "Merkava": "https://www.dustloop.com/wiki/index.php?title=BBTag/Merkava",
    "Vatista": "https://www.dustloop.com/wiki/index.php?title=BBTag/Vatista",
    "Seth": "https://www.dustloop.com/wiki/index.php?title=BBTag/Seth",
    "Yuzuriha": "https://www.dustloop.com/wiki/index.php?title=BBTag/Yuzuriha",
    "Hilda": "https://www.dustloop.com/wiki/index.php?title=BBTag/Hilda",
    "Mika": "https://www.dustloop.com/wiki/index.php?title=BBTag/Mika",
    # RWBY #
    "Ruby_Rose": "https://www.dustloop.com/wiki/index.php?title=BBTag/Ruby_Rose",
    "Weiss_Schnee": "https://www.dustloop.com/wiki/index.php?title=BBTag/Weiss_Schnee",
    "Blake_Belladonna": "https://www.dustloop.com/wiki/index.php?title=BBTag/Blake_Belladonna",
    "Yang_Xiao_Long": "https://www.dustloop.com/wiki/index.php?title=BBTag/Yang_Xiao_Long",
    "Neo_Politan": "https://www.dustloop.com/wiki/index.php?title=BBTag/Neo_Politan",

    # Others #
    "Heart_Aino": "https://www.dustloop.com/wiki/index.php?title=BBTag/Heart_Aino",
    "Yumi": "https://www.dustloop.com/wiki/index.php?title=BBTag/Yumi",
    "Akatsuki": "https://www.dustloop.com/wiki/index.php?title=BBTag/Akatsuki",
    "Blitztank": "https://www.dustloop.com/wiki/index.php?title=BBTag/Blitztank"
}

GGXRDREV2 = {
    "Answer": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Answer",
    "Axl_Low": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Axl_Low",
    "Baiken": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Baiken",
    "Bedman": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Bedman",
    "Chipp_Zanuff": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Chipp_Zanuff",
    "Dizzy": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Dizzy",
    "Elphelt_Valentine": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Elphelt_Valentine",
    "Faust": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Faust",
    "I-No": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/I-No",
    "Jack-O'": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Jack-O'",
    "Jam_Kuradoberi": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Jam_Kuradoberi",
    "Johnny": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Johnny",
    "Kum_Haehyun": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Kum_Haehyun",
    "Ky_Kiske": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Ky_Kiske",
    "Leo_Whitefang": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Leo_Whitefang",
    "May": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/May",
    "Millia_Rage": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Millia_Rage",
    "Potemkin": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Potemkin",
    "Ramlethal_Valentine": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Ramlethal_Valentine",
    "Raven": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Raven",
    "Sin_Kiske": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Sin_Kiske",
    "Slayer": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Slayer",
    "Sol_Badguy": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Sol_Badguy",
    "Venom": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Venom",
    "Zato-1": "https://www.dustloop.com/wiki/index.php?title=GGXRD-R2/Zato-1"
}

BBCF = {
    "Amane_Nishiki": "https://www.dustloop.com/wiki/index.php?title=BBCF/Amane_Nishiki",
    "Arakune": "https://www.dustloop.com/wiki/index.php?title=BBCF/Arakune",
    "Azrael": "https://www.dustloop.com/wiki/index.php?title=BBCF/Azrael",
    "Bang_Shishigami": "https://www.dustloop.com/wiki/index.php?title=BBCF/Bang_Shishigami",
    "Bullet": "https://www.dustloop.com/wiki/index.php?title=BBCF/Bullet",
    "Carl_Clover": "https://www.dustloop.com/wiki/index.php?title=BBCF/Carl_Clover",
    "Celica_A._Mercury": "https://www.dustloop.com/wiki/index.php?title=BBCF/Celica_A._Mercury",
    "Es": "https://www.dustloop.com/wiki/index.php?title=BBCF/Es",
    "Hakumen": "https://www.dustloop.com/wiki/index.php?title=BBCF/Hakumen",
    "Hazama": "https://www.dustloop.com/wiki/index.php?title=BBCF/Hazama",
    "Hibiki_Kohaku": "https://www.dustloop.com/wiki/index.php?title=BBCF/Hibiki_Kohaku",
    "Izanami": "https://www.dustloop.com/wiki/index.php?title=BBCF/Izanami",
    "Izayoi": "https://www.dustloop.com/wiki/index.php?title=BBCF/Izayoi",
    "Jin_Kisaragi": "https://www.dustloop.com/wiki/index.php?title=BBCF/Jin_Kisaragi",
    "Jubei": "https://www.dustloop.com/wiki/index.php?title=BBCF/Jubei",
    "Kagura_Mutsuki": "https://www.dustloop.com/wiki/index.php?title=BBCF/Kagura_Mutsuki",
    "Kokonoe": "https://www.dustloop.com/wiki/index.php?title=BBCF/Kokonoe",
    "Litchi_Faye_Ling": "https://www.dustloop.com/wiki/index.php?title=BBCF/Litchi_Faye_Ling",
    "Makoto_Nanaya": "https://www.dustloop.com/wiki/index.php?title=BBCF/Makoto_Nanaya",
    "Mai_Natsume": "https://www.dustloop.com/wiki/index.php?title=BBCF/Mai_Natsume",
    "Naoto_Kurogane": "https://www.dustloop.com/wiki/index.php?title=BBCF/Naoto_Kurogane",
    "Nine_the_Phantom": "https://www.dustloop.com/wiki/index.php?title=BBCF/Nine_the_Phantom",
    "Noel_Vermillion": "https://www.dustloop.com/wiki/index.php?title=BBCF/Noel_Vermillion",
    "Platinum_the_Trinity": "https://www.dustloop.com/wiki/index.php?title=BBCF/Platinum_the_Trinity",
    "Rachel_Alucard": "https://www.dustloop.com/wiki/index.php?title=BBCF/Rachel_Alucard",
    "Ragna_the_Bloodedge": "https://www.dustloop.com/wiki/index.php?title=BBCF/Ragna_the_Bloodedge",
    "Relius_Clover": "https://www.dustloop.com/wiki/index.php?title=BBCF/Relius_Clover",
    "Susano'o": "https://www.dustloop.com/wiki/index.php?title=BBCF/Susano'o",
    "Iron_Tager": "https://www.dustloop.com/wiki/index.php?title=BBCF/Iron_Tager",
    "Taokaka": "https://www.dustloop.com/wiki/index.php?title=BBCF/Taokaka",
    "Tsubaki_Yayoi": "https://www.dustloop.com/wiki/index.php?title=BBCF/Tsubaki_Yayoi",
    "Yuuki_Terumi": "https://www.dustloop.com/wiki/index.php?title=BBCF/Yuuki_Terumi",
    "Valkenhayn_R._Hellsing": "https://www.dustloop.com/wiki/index.php?title=BBCF/Valkenhayn_R._Hellsing",
    "Lambda-11": "https://www.dustloop.com/wiki/index.php?title=BBCF/Lambda-11",
    "Mu-12": "https://www.dustloop.com/wiki/index.php?title=BBCF/Mu-12",
    "Nu-13": "https://www.dustloop.com/wiki/index.php?title=BBCF/Nu-13"
}

UNICLR = {
    "Hyde": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Hyde",
    "Linne": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Linne",
    "Waldstein": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Waldstein",
    "Carmine": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Carmine",
    "Orie": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Orie",
    "Gordeau": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Gordeau",
    "Merkava": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Merkava",
    "Vatista": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Vatista",
    "Seth": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Seth",
    "Yuzuriha": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Yuzuriha",
    "Hilda": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Hilda",
    "Chaos": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Chaos",
    "Nanase": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Nanase",
    "Byakuya": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Byakuya",
    "Phonon": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Phonon",
    "Mika": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Mika",
    "Wagner": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Wagner",
    "Enkidu": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Enkidu",
    "Londrekia": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Londrekia",
    "Eltnum": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Eltnum",
    "Akatsuki": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Akatsuki"
}

GAMES = {
    "P4AU": P4AU,
    "DBFZ": DBFZ,
    "GBVS": GBVS,
    "BBTAG": BBTAG,
    "GGXRDREV2": GGXRDREV2,
    "BBCF": BBCF,
    "UNICLR": UNICLR
}
