HOST = "https://www.dustloop.com/wiki"

P4AU = {
    "Aigis": (f"{HOST}/index.php?title=P4AU/Aigis", f"{HOST}/images/thumb/8/8c/P4AU_Aigis_portrait.png/80px-P4AU_Aigis_portrait.png"),
    "Akihiko_Sanada": (f"{HOST}/index.php?title=P4AU/Akihiko_Sanada", f"{HOST}/images/thumb/4/47/P4AU_Akihiko_portrait.png/80px-P4AU_Akihiko_portrait.png"),
    "Chie_Satonaka": (f"{HOST}/index.php?title=P4AU/Chie_Satonaka", f"{HOST}/images/thumb/5/53/P4AU_Chie_portrait.png/80px-P4AU_Chie_portrait.png"),
    "Elizabeth": (f"{HOST}/index.php?title=P4AU/Elizabeth", f"{HOST}/images/thumb/0/07/P4AU_Elizabeth_portrait.png/80px-P4AU_Elizabeth_portrait.png"),
    "Junpei_Iori": (f"{HOST}/index.php?title=P4AU/Junpei_Iori", f"{HOST}/images/thumb/c/cb/P4AU_Junpei_portrait.png/80px-P4AU_Junpei_portrait.png"),
    "Kanji_Tatsumi": (f"{HOST}/index.php?title=P4AU/Kanji_Tatsumi", f"{HOST}/images/thumb/3/39/P4AU_Kanji_portrait.png/80px-P4AU_Kanji_portrait.png"),
    "Ken_Amada": (f"{HOST}/index.php?title=P4AU/Ken_Amada", f"{HOST}/images/thumb/c/ce/P4AU_Ken_portrait.png/80px-P4AU_Ken_portrait.png"),
    "Labrys": (f"{HOST}/index.php?title=P4AU/Labrys", f"{HOST}/images/thumb/5/5d/P4AU_Labrys_portrait.png/80px-P4AU_Labrys_portrait.png"),
    "Margaret": (f"{HOST}/index.php?title=P4AU/Margaret", f"{HOST}/images/thumb/6/69/P4AU_Margaret_portrait.png/80px-P4AU_Margaret_portrait.png"),
    "Marie": (f"{HOST}/index.php?title=P4AU/Marie", f"{HOST}/images/thumb/5/54/P4AU_Marie_portrait.png/80px-P4AU_Marie_portrait.png"),
    "Sho_MINAZUKI": (f"{HOST}/index.php?title=P4AU/Sho_MINAZUKI", f"{HOST}/images/thumb/2/2a/P4AU_PSho_portrait.png/80px-P4AU_PSho_portrait.png"),
    "Mitsuru_Kirijo": (f"{HOST}/index.php?title=P4AU/Mitsuru_Kirijo", f"{HOST}/images/thumb/5/54/P4AU_Mitsuru_portrait.png/80px-P4AU_Mitsuru_portrait.png"),
    "Naoto_Shirogane": (f"{HOST}/index.php?title=P4AU/Naoto_Shirogane", f"{HOST}/images/thumb/3/32/P4AU_Naoto_portrait.png/80px-P4AU_Naoto_portrait.png"),
    "Rise_Kujikawa": (f"{HOST}/index.php?title=P4AU/Rise_Kujikawa", f"{HOST}/images/thumb/b/b9/P4AU_Rise_portrait.png/80px-P4AU_Rise_portrait.png"),
    "Shadow_Labrys": (f"{HOST}/index.php?title=P4AU/Shadow_Labrys", f"{HOST}/images/thumb/4/43/P4AU_SLabrys_portrait.png/80px-P4AU_SLabrys_portrait.png"),
    "SHO_Minazuki": (f"{HOST}/index.php?title=P4AU/SHO_Minazuki", f"{HOST}/images/thumb/7/7b/P4AU_Sho_portrait.png/80px-P4AU_Sho_portrait.png"),
    "Teddie": (f"{HOST}/index.php?title=P4AU/Teddie", f"{HOST}/images/thumb/c/c2/P4AU_Teddie_portrait.png/80px-P4AU_Teddie_portrait.png"),
    "Tohru_Adachi": (f"{HOST}/index.php?title=P4AU/Tohru_Adachi", f"{HOST}/images/thumb/7/70/P4AU_Adachi_portrait.png/80px-P4AU_Adachi_portrait.png"),
    "Yosuke_Hanamura": (f"{HOST}/index.php?title=P4AU/Yosuke_Hanamura", f"{HOST}/images/thumb/2/23/P4AU_Yosuke_portrait.png/80px-P4AU_Yosuke_portrait.png"),
    "Yu_Narukami": (f"{HOST}/index.php?title=P4AU/Yu_Narukami", f"{HOST}/images/thumb/4/45/P4AU_Yu_portrait.png/80px-P4AU_Yu_portrait.png"),
    "Yukari_Takeba": (f"{HOST}/index.php?title=P4AU/Yukari_Takeba", f"{HOST}/images/thumb/4/40/P4AU_Yukari_portrait.png/80px-P4AU_Yukari_portrait.png"),
    "Yukiko_Amagi": (f"{HOST}/index.php?title=P4AU/Yukiko_Amagi", f"{HOST}/images/thumb/a/ae/P4AU_Yukiko_portrait.png/80px-P4AU_Yukiko_portrait.png")
    }

""" DBFZ = {
    "Android_16": (f"{HOST}/index.php?title=DBFZ/Android_16",
    "Android_17": (f"{HOST}/index.php?title=DBFZ/Android_17",
    "Android_18": (f"{HOST}/index.php?title=DBFZ/Android_18",
    "Android 21": (f"{HOST}/index.php?title=DBFZ/Android_21",
    "Bardock": (f"{HOST}/index.php?title=DBFZ/Bardock",
    "Beerus": (f"{HOST}/index.php?title=DBFZ/Beerus",
    "Broley": (f"{HOST}/index.php?title=DBFZ/Broly",
    "DBS_Broley": (f"{HOST}/index.php?title=DBFZ/DBS_Broly",
    "Captain_Ginyu": (f"{HOST}/index.php?title=DBFZ/Captain_Ginyu",
    "Cell": (f"{HOST}/index.php?title=DBFZ/Cell",
    "Cooler": (f"{HOST}/index.php?title=DBFZ/Cooler",
    "Frieza": (f"{HOST}/index.php?title=DBFZ/Frieza",
    "SSB_Gogeta": (f"{HOST}/index.php?title=DBFZ/SSB_Gogeta",
    "Teen_Gohan": (f"{HOST}/index.php?title=DBFZ/Teen_Gohan",
    "Adult_Gohan": (f"{HOST}/index.php?title=DBFZ/Adult_Gohan",
    "Goku": (f"{HOST}/index.php?title=DBFZ/Goku",
    "SS_Goku": (f"{HOST}/index.php?title=DBFZ/SS_Goku",
    "SSB_Goku": (f"{HOST}/index.php?title=DBFZ/SSB_Goku",
    "UI_Goku": (f"{HOST}/index.php?title=DBFZ/UI_Goku",
    "GT_Goku": (f"{HOST}/index.php?title=DBFZ/GT_Goku",
    "Goku_Black": (f"{HOST}/index.php?title=DBFZ/Goku_Black",
    "Gotenks": (f"{HOST}/index.php?title=DBFZ/Gotenks",
    "Hit": (f"{HOST}/index.php?title=DBFZ/Hit",
    "Janemba": (f"{HOST}/index.php?title=DBFZ/Janemba",
    "Jiren": (f"{HOST}/index.php?title=DBFZ/Jiren",
    "Kefla": (f"{HOST}/index.php?title=DBFZ/Kefla",
    "Kid_Buu": (f"{HOST}/index.php?title=DBFZ/Kid_Buu",
    "Krilin": (f"{HOST}/index.php?title=DBFZ/Krillin",
    "Majin_Buu": (f"{HOST}/index.php?title=DBFZ/Majin_Buu",
    "Nappa": (f"{HOST}/index.php?title=DBFZ/Nappa",
    "Piccolo": (f"{HOST}/index.php?title=DBFZ/Piccolo",
    "Tien": (f"{HOST}/index.php?title=DBFZ/Tien",
    "Trunks": (f"{HOST}/index.php?title=DBFZ/Trunks",
    "Vegeta": (f"{HOST}/index.php?title=DBFZ/Vegeta",
    "SS_Vegeta": (f"{HOST}/index.php?title=DBFZ/SS_Vegeta",
    "SSB_Vegeta": (f"{HOST}/index.php?title=DBFZ/SSB_Vegeta",
    "SSB_Vegito": (f"{HOST}/index.php?title=DBFZ/SSB_Vegito",
    "Videl": (f"{HOST}/index.php?title=DBFZ/Videl",
    "Yamcha": (f"{HOST}/index.php?title=DBFZ/Yamcha",
    "Fused_Zamasu": (f"{HOST}/index.php?title=DBFZ/Fused_Zamasu"
}

GBVS = {
    "Beelzebub": (f"{HOST}/index.php?title=GBVS/Beelzebub",
    "Belial": (f"{HOST}/index.php?title=GBVS/Belial",
    "Charlotta": (f"{HOST}/index.php?title=GBVS/Charlotta",
    "Djeeta": (f"{HOST}/index.php?title=GBVS/Djeeta",
    "Ferry": (f"{HOST}/index.php?title=GBVS/Ferry",
    "Gran": (f"{HOST}/index.php?title=GBVS/Gran",
    "Katalina": (f"{HOST}/index.php?title=GBVS/Katalina",
    "Ladiva": (f"{HOST}/index.php?title=GBVS/Ladiva",
    "Lancelot": (f"{HOST}/index.php?title=GBVS/Lancelot",
    "Lowain": (f"{HOST}/index.php?title=GBVS/Lowain",
    "Metera": (f"{HOST}/index.php?title=GBVS/Metera",
    "Narmaya": (f"{HOST}/index.php?title=GBVS/Narmaya",
    "Percival": (f"{HOST}/index.php?title=GBVS/Percival",
    "Soriz": (f"{HOST}/index.php?title=GBVS/Soriz",
    "Vaseraga": (f"{HOST}/index.php?title=GBVS/Vaseraga",
    "Zeta": (f"{HOST}/index.php?title=GBVS/Zeta",
    "Zooey": (f"{HOST}/index.php?title=GBVS/Zooey"
}

BBTAG = {
    # Blaz Blue #
    "Ragna_the_Bloodedge": (f"{HOST}/index.php?title=BBTag/Ragna_the_Bloodedge",
    "Jin_Kisaragi": (f"{HOST}/index.php?title=BBTag/Jin_Kisaragi",
    "Noel_Vermillion": (f"{HOST}/index.php?title=BBTag/Noel_Vermillion",
    "Rachel_Alucard": (f"{HOST}/index.php?title=BBTag/Rachel_Alucard",
    "Iron_Tager": (f"{HOST}/index.php?title=BBTag/Iron_Tager",
    "Hakumen": (f"{HOST}/index.php?title=BBTag/Hakumen",
    "Nu-13": (f"{HOST}/index.php?title=BBTag/Nu-13",
    "Hazama": (f"{HOST}/index.php?title=BBTag/Hazama",
    "Makoto_Nanaya": (f"{HOST}/index.php?title=BBTag/Makoto_Nanaya",
    "Platinum_the_Trinity": (f"{HOST}/index.php?title=BBTag/Platinum_the_Trinity",
    "Izayoi": (f"{HOST}/index.php?title=BBTag/Izayoi",
    "Azrael": (f"{HOST}/index.php?title=BBTag/Azrael",
    "Celica_A._Mercury": (f"{HOST}/index.php?title=BBTag/Celica_A._Mercury",
    "Nine_the_Phantom": (f"{HOST}/index.php?title=BBTag/Nine_the_Phantom",
    "Naoto_Kurogane": (f"{HOST}/index.php?title=BBTag/Naoto_Kurogane",
    "Susano'o": (f"{HOST}/index.php?title=BBTag/Susano'o",
    "Es": (f"{HOST}/index.php?title=BBTag/Es",
    "Mai_Natsume": (f"{HOST}/index.php?title=BBTag/Mai_Natsume",
    "Jubei": (f"{HOST}/index.php?title=BBTag/Jubei",

    # Persona 4 #
    "Yu_Narukami": (f"{HOST}/index.php?title=BBTag/Yu_Narukami",
    "Yosuke_Hanamura": (f"{HOST}/index.php?title=BBTag/Yosuke_Hanamura",
    "Chie_Satonaka": (f"{HOST}/index.php?title=BBTag/Chie_Satonaka",
    "Yukiko_Amagi": (f"{HOST}/index.php?title=BBTag/Yukiko_Amagi",
    "Kanji_Tatsumi": (f"{HOST}/index.php?title=BBTag/Kanji_Tatsumi",
    "Teddie": (f"{HOST}/index.php?title=BBTag/Teddie",
    "Naoto_Shirogane": (f"{HOST}/index.php?title=BBTag/Naoto_Shirogane",
    "Mitsuru_Kirijo": (f"{HOST}/index.php?title=BBTag/Mitsuru_Kirijo",
    "Akihiko_Sanada": (f"{HOST}/index.php?title=BBTag/Akihiko_Sanada",
    "Aegis": (f"{HOST}/index.php?title=BBTag/Aegis",
    "Elizabeth": (f"{HOST}/index.php?title=BBTag/Elizabeth",
    "Labrys": (f"{HOST}/index.php?title=BBTag/Labrys",
    "Tohru_Adachi": (f"{HOST}/index.php?title=BBTag/Tohru_Adachi",

    # Under Night In-Birth #
    "Hyde": (f"{HOST}/index.php?title=BBTag/Hyde",
    "Linne": (f"{HOST}/index.php?title=BBTag/Linne",
    "Waldstein": (f"{HOST}/index.php?title=BBTag/Waldstein",
    "Carmine": (f"{HOST}/index.php?title=BBTag/Carmine",
    "Orie": (f"{HOST}/index.php?title=BBTag/Orie",
    "Gordeau": (f"{HOST}/index.php?title=BBTag/Gordeau",
    "Merkava": (f"{HOST}/index.php?title=BBTag/Merkava",
    "Vatista": (f"{HOST}/index.php?title=BBTag/Vatista",
    "Seth": (f"{HOST}/index.php?title=BBTag/Seth",
    "Yuzuriha": (f"{HOST}/index.php?title=BBTag/Yuzuriha",
    "Hilda": (f"{HOST}/index.php?title=BBTag/Hilda",
    "Mika": (f"{HOST}/index.php?title=BBTag/Mika",
    # RWBY #
    "Ruby_Rose": (f"{HOST}/index.php?title=BBTag/Ruby_Rose",
    "Weiss_Schnee": (f"{HOST}/index.php?title=BBTag/Weiss_Schnee",
    "Blake_Belladonna": (f"{HOST}/index.php?title=BBTag/Blake_Belladonna",
    "Yang_Xiao_Long": (f"{HOST}/index.php?title=BBTag/Yang_Xiao_Long",
    "Neo_Politan": (f"{HOST}/index.php?title=BBTag/Neo_Politan",

    # Others #
    "Heart_Aino": (f"{HOST}/index.php?title=BBTag/Heart_Aino",
    "Yumi": (f"{HOST}/index.php?title=BBTag/Yumi",
    "Akatsuki": (f"{HOST}/index.php?title=BBTag/Akatsuki",
    "Blitztank": (f"{HOST}/index.php?title=BBTag/Blitztank"
}

GGXRDREV2 = {
    "Answer": (f"{HOST}/index.php?title=GGXRD-R2/Answer",
    "Axl_Low": (f"{HOST}/index.php?title=GGXRD-R2/Axl_Low",
    "Baiken": (f"{HOST}/index.php?title=GGXRD-R2/Baiken",
    "Bedman": (f"{HOST}/index.php?title=GGXRD-R2/Bedman",
    "Chipp_Zanuff": (f"{HOST}/index.php?title=GGXRD-R2/Chipp_Zanuff",
    "Dizzy": (f"{HOST}/index.php?title=GGXRD-R2/Dizzy",
    "Elphelt_Valentine": (f"{HOST}/index.php?title=GGXRD-R2/Elphelt_Valentine",
    "Faust": (f"{HOST}/index.php?title=GGXRD-R2/Faust",
    "I-No": (f"{HOST}/index.php?title=GGXRD-R2/I-No",
    "Jack-O'": (f"{HOST}/index.php?title=GGXRD-R2/Jack-O'",
    "Jam_Kuradoberi": (f"{HOST}/index.php?title=GGXRD-R2/Jam_Kuradoberi",
    "Johnny": (f"{HOST}/index.php?title=GGXRD-R2/Johnny",
    "Kum_Haehyun": (f"{HOST}/index.php?title=GGXRD-R2/Kum_Haehyun",
    "Ky_Kiske": (f"{HOST}/index.php?title=GGXRD-R2/Ky_Kiske",
    "Leo_Whitefang": (f"{HOST}/index.php?title=GGXRD-R2/Leo_Whitefang",
    "May": (f"{HOST}/index.php?title=GGXRD-R2/May",
    "Millia_Rage": (f"{HOST}/index.php?title=GGXRD-R2/Millia_Rage",
    "Potemkin": (f"{HOST}/index.php?title=GGXRD-R2/Potemkin",
    "Ramlethal_Valentine": (f"{HOST}/index.php?title=GGXRD-R2/Ramlethal_Valentine",
    "Raven": (f"{HOST}/index.php?title=GGXRD-R2/Raven",
    "Sin_Kiske": (f"{HOST}/index.php?title=GGXRD-R2/Sin_Kiske",
    "Slayer": (f"{HOST}/index.php?title=GGXRD-R2/Slayer",
    "Sol_Badguy": (f"{HOST}/index.php?title=GGXRD-R2/Sol_Badguy",
    "Venom": (f"{HOST}/index.php?title=GGXRD-R2/Venom",
    "Zato-1": (f"{HOST}/index.php?title=GGXRD-R2/Zato-1"
}

BBCF = {
    "Amane_Nishiki": (f"{HOST}/index.php?title=BBCF/Amane_Nishiki",
    "Arakune": (f"{HOST}/index.php?title=BBCF/Arakune",
    "Azrael": (f"{HOST}/index.php?title=BBCF/Azrael",
    "Bang_Shishigami": (f"{HOST}/index.php?title=BBCF/Bang_Shishigami",
    "Bullet": (f"{HOST}/index.php?title=BBCF/Bullet",
    "Carl_Clover": (f"{HOST}/index.php?title=BBCF/Carl_Clover",
    "Celica_A._Mercury": (f"{HOST}/index.php?title=BBCF/Celica_A._Mercury",
    "Es": (f"{HOST}/index.php?title=BBCF/Es",
    "Hakumen": (f"{HOST}/index.php?title=BBCF/Hakumen",
    "Hazama": (f"{HOST}/index.php?title=BBCF/Hazama",
    "Hibiki_Kohaku": (f"{HOST}/index.php?title=BBCF/Hibiki_Kohaku",
    "Izanami": (f"{HOST}/index.php?title=BBCF/Izanami",
    "Izayoi": (f"{HOST}/index.php?title=BBCF/Izayoi",
    "Jin_Kisaragi": (f"{HOST}/index.php?title=BBCF/Jin_Kisaragi",
    "Jubei": (f"{HOST}/index.php?title=BBCF/Jubei",
    "Kagura_Mutsuki": (f"{HOST}/index.php?title=BBCF/Kagura_Mutsuki",
    "Kokonoe": (f"{HOST}/index.php?title=BBCF/Kokonoe",
    "Litchi_Faye_Ling": (f"{HOST}/index.php?title=BBCF/Litchi_Faye_Ling",
    "Makoto_Nanaya": (f"{HOST}/index.php?title=BBCF/Makoto_Nanaya",
    "Mai_Natsume": (f"{HOST}/index.php?title=BBCF/Mai_Natsume",
    "Naoto_Kurogane": (f"{HOST}/index.php?title=BBCF/Naoto_Kurogane",
    "Nine_the_Phantom": (f"{HOST}/index.php?title=BBCF/Nine_the_Phantom",
    "Noel_Vermillion": (f"{HOST}/index.php?title=BBCF/Noel_Vermillion",
    "Platinum_the_Trinity": (f"{HOST}/index.php?title=BBCF/Platinum_the_Trinity",
    "Rachel_Alucard": (f"{HOST}/index.php?title=BBCF/Rachel_Alucard",
    "Ragna_the_Bloodedge": (f"{HOST}/index.php?title=BBCF/Ragna_the_Bloodedge",
    "Relius_Clover": (f"{HOST}/index.php?title=BBCF/Relius_Clover",
    "Susano'o": (f"{HOST}/index.php?title=BBCF/Susano'o",
    "Iron_Tager": (f"{HOST}/index.php?title=BBCF/Iron_Tager",
    "Taokaka": (f"{HOST}/index.php?title=BBCF/Taokaka",
    "Tsubaki_Yayoi": (f"{HOST}/index.php?title=BBCF/Tsubaki_Yayoi",
    "Yuuki_Terumi": (f"{HOST}/index.php?title=BBCF/Yuuki_Terumi",
    "Valkenhayn_R._Hellsing": (f"{HOST}/index.php?title=BBCF/Valkenhayn_R._Hellsing",
    "Lambda-11": (f"{HOST}/index.php?title=BBCF/Lambda-11",
    "Mu-12": (f"{HOST}/index.php?title=BBCF/Mu-12",
    "Nu-13": (f"{HOST}/index.php?title=BBCF/Nu-13"
}

UNICLR = {
    "Hyde": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Hyde",
    "Linne": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Linne",
    "Waldstein": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Waldstein",
    "Carmine": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Carmine",
    "Orie": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Orie",
    "Gordeau": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Gordeau",
    "Merkava": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Merkava",
    "Vatista": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Vatista",
    "Seth": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Seth",
    "Yuzuriha": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Yuzuriha",
    "Hilda": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Hilda",
    "Chaos": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Chaos",
    "Nanase": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Nanase",
    "Byakuya": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Byakuya",
    "Phonon": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Phonon",
    "Mika": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Mika",
    "Wagner": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Wagner",
    "Enkidu": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Enkidu",
    "Londrekia": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Londrekia",
    "Eltnum": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Eltnum",
    "Akatsuki": "http://wiki.mizuumi.net/w/Under_Night_In-Birth/UNICLR/Akatsuki"
}

GAMES = {
    "P4AU": P4AU,
    "DBFZ": DBFZ,
    "GBVS": GBVS,
    "BBTAG": BBTAG,
    "GGXRDREV2": GGXRDREV2,
    "BBCF": BBCF,
    "UNICLR": UNICLR
} """

GAMES = {"P4AU": P4AU}
